# azure-pipelines.yml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
# install ansible
- script: sudo ./install-ansible.sh

# ansible
- task: Ansible@0
  displayName: Run playbook
  inputs: {
    ansibleInterface: agentMachine,
    playbookPathOnAgentMachine: 'ansible/pipelines.yml',
    inventoriesAgentMachine: 'file',
    inventoryFileOnAgentMachine: 'ansible/inventory'
  }
