---

- hosts: 127.0.0.1
  connection: local
  remote_user: "{{ lookup('env', 'USER') }}"

  post_tasks:

    - name: test neovim plugins
      shell: "nvim -E +':source $HOME/.config/nvim/init.vim' +'redir>>/dev/stdout | :source {{ playbook_dir }}/../vim/test-plugins.vim | redir END' -scq!"
      register: nvim_test_result

    - assert:
        that:
          - "'Plugins not installed' not in nvim_test_result.stdout"
        fail_msg: " {{ nvim_test_result.stdout }} "

