---

- hosts: 127.0.0.1
  connection: local
  remote_user: "{{ lookup('env', 'USER') }}"

  post_tasks:

    - name: ls
      command: ls -l
      register: ls_output

    - name: test
      debug:
        msg: "{{ ls_output.stdout }}"

